global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'psychsync-api'
    static_configs:
      - targets: ['localhost:8000']
  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:5555']


